### ISSUE TITLE
Doesn't work with mac

### ISSUE THREAD

**Issue by vemkiran** [OpenXenManager/openxenmanager#77]
It's either I am not using the correct file to run OXM on mac.
I am running oxm.pyw and openxenmanager that are created in the directory after i do build and setup.

or it doesn't work wit mac.

If it is the wrong file I'm running, could you guys have some INSTALL file with installation instructions and running instructions?

Thanks

Traceback (most recent call last):
  File "oxm.pyw", line 34, in <module>
    wine = oxcWindow()
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py", line 170, in __init__
    self.config = ConfigObj(pathconfig) 
  File "/usr/local/lib/python2.7/site-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python2.7/site-packages/configobj.py", line 1287, in _load
    content = self._handle_bom(content)
  File "/usr/local/lib/python2.7/site-packages/configobj.py", line 1477, in _handle_bom
    if six.PY2 and isinstance(line, str):
AttributeError: 'module' object has no attribute 'PY2'
Exiting...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py", line 1616, in signal_handler
    self.config.write()
AttributeError: 'oxcWindow' object has no attribute 'config'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py", line 1616, in signal_handler
    self.config.write()

**Comment by dlintott** [comment]
You probably need to upgrade the six package using 

``` pip install --upgrade six```

**Comment by sfransen** [comment]
no such file as pip

**Comment by nkcanball** [comment]
I can say that as of commit bceaaefdeaca1c06bb2a6e3dbb861954071980ba - Aug 20, that quite a few of the basic functionality I used (create, start/stop, reboot) work on a Mac 10.10.5 with the following issues/workarounds:
- using the password manager breaks (auto or not) re-connecting to servers on restarting OXM. Reconnect providing password works fine
- default values (e.g., net iface) when creating VMs from template doesn't work. explicitly adding one works
- VM upon creation doesn't showup on the server's list of VMs - there's no refresh button either. restarting the OXM shows the created VM
- Console doesn't seem to work 
- Details of network interface on network tab dissappears after clicking through other tabs!
